import type { Farm, Cooperative, Investment, Transaction } from '@/lib/types'

export const MOCK_COOPERATIVES: Cooperative[] = [
  {
    id: 'coop-4',
    name: 'Atok Farmers Cooperative',
    barangay: 'Atok',
    municipality: 'Benguet',
    walletAddress: 'GCOOPATOKBENGETAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    verifiedStatus: true,
    totalEarnings: 4500.0,
    description: 'Highland vegetable and strawberry farming cooperative in Benguet.',
    createdAt: '2024-01-10T00:00:00Z',
    _count: { farms: 15 },
  },
  {
    id: 'coop-1',
    name: 'Sta. Rosa Agricultural Cooperative',
    barangay: 'Sta. Rosa',
    municipality: 'Laguna',
    walletAddress: 'GCOOPSTAROSAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    verifiedStatus: true,
    totalEarnings: 2450.5,
    description: 'Serving 200+ farmers in Sta. Rosa, Laguna since 1998.',
    createdAt: '2024-01-01T00:00:00Z',
    _count: { farms: 12 },
  },
  {
    id: 'coop-2',
    name: 'Bukidnon Highlands Farmers Coop',
    barangay: 'Valencia',
    municipality: 'Bukidnon',
    walletAddress: 'GCOOPBUKIDNONAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    verifiedStatus: true,
    totalEarnings: 3120.0,
    description: 'Highland vegetable and corn farming cooperative.',
    createdAt: '2024-02-15T00:00:00Z',
    _count: { farms: 8 },
  },
  {
    id: 'coop-3',
    name: 'Pampanga Rice Growers Alliance',
    barangay: 'San Fernando',
    municipality: 'Pampanga',
    walletAddress: 'GCOOPPAMPANGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    verifiedStatus: false,
    totalEarnings: 980.0,
    description: 'Rice and palay producers across Central Luzon.',
    createdAt: '2024-03-10T00:00:00Z',
    _count: { farms: 5 },
  },
]

export const MOCK_FARMS: Farm[] = [
  {
    id: 'farm-1',
    name: 'Verde Rice Terraces',
    cropType: 'Rice (Palay)',
    livestockType: undefined,
    description:
      'Traditional rice farming using sustainable water irrigation systems in Laguna. Expected 3 harvests per year with premium organic certification.',
    location: 'Sta. Rosa, Laguna',
    fundingGoal: 5000,
    currentFunding: 3750,
    expectedYield: '8 metric tons',
    expectedReturn: 18,
    riskLevel: 'LOW',
    duration: 120,
    harvestSchedule: 'August – September 2025',
    status: 'ACTIVE',
    contractAddress: 'CCONTRACTAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA1',
    farmerWallet: 'GFARMER1AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    cooperativeId: 'coop-1',
    cooperative: MOCK_COOPERATIVES[0],
    cooperativeEnabled: true,
    weatherRisk: 'LOW',
    createdAt: '2025-03-01T00:00:00Z',
    updatedAt: '2025-05-01T00:00:00Z',
    _count: { investments: 14 },
  },
  {
    id: 'farm-2',
    name: 'Bukidnon Corn Highlands',
    cropType: 'White Corn',
    livestockType: undefined,
    description:
      'Premium white corn cultivation in the fertile Bukidnon highlands. Direct supply contracts with major food processing companies.',
    location: 'Valencia, Bukidnon',
    fundingGoal: 8000,
    currentFunding: 5600,
    expectedYield: '15 metric tons',
    expectedReturn: 22,
    riskLevel: 'MEDIUM',
    duration: 90,
    harvestSchedule: 'September 2025',
    status: 'ACTIVE',
    contractAddress: 'CCONTRACTBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB2',
    farmerWallet: 'GFARMER2BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
    cooperativeId: 'coop-2',
    cooperative: MOCK_COOPERATIVES[1],
    cooperativeEnabled: true,
    weatherRisk: 'MODERATE',
    createdAt: '2025-03-15T00:00:00Z',
    updatedAt: '2025-05-05T00:00:00Z',
    _count: { investments: 22 },
  },
  {
    id: 'farm-3',
    name: 'Pampanga Free-Range Hog Farm',
    cropType: undefined,
    livestockType: 'Hogs (Native + Commercial)',
    description:
      'Free-range hog farming with biosecurity protocols. Market-ready hogs in 6 months with guaranteed buyer through LGU program.',
    location: 'San Fernando, Pampanga',
    fundingGoal: 12000,
    currentFunding: 4200,
    expectedYield: '50 heads market weight',
    expectedReturn: 28,
    riskLevel: 'MEDIUM',
    duration: 180,
    harvestSchedule: 'November 2025',
    status: 'ACTIVE',
    contractAddress: 'CCONTRACTCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC3',
    farmerWallet: 'GFARMER3CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
    cooperativeId: undefined,
    cooperative: undefined,
    cooperativeEnabled: false,
    weatherRisk: 'MODERATE',
    createdAt: '2025-04-01T00:00:00Z',
    updatedAt: '2025-05-10T00:00:00Z',
    _count: { investments: 9 },
  },
  {
    id: 'farm-4',
    name: 'Ilocos Garlic & Onion Farm',
    cropType: 'Garlic & Sibuyas',
    livestockType: undefined,
    description:
      'Premium Ilocos garlic and sibuyas Tagalog. High-value crops with consistent demand year-round. Organic and export-quality produce.',
    location: 'Batac, Ilocos Norte',
    fundingGoal: 6500,
    currentFunding: 6500,
    expectedYield: '5 metric tons garlic, 3 MT onion',
    expectedReturn: 35,
    riskLevel: 'LOW',
    duration: 150,
    harvestSchedule: 'July 2025',
    status: 'FUNDED',
    contractAddress: 'CCONTRACTDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD4',
    farmerWallet: 'GFARMER4DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
    cooperativeId: undefined,
    cooperative: undefined,
    cooperativeEnabled: false,
    weatherRisk: 'LOW',
    createdAt: '2025-02-01T00:00:00Z',
    updatedAt: '2025-04-20T00:00:00Z',
    _count: { investments: 31 },
  },
  {
    id: 'farm-5',
    name: 'Davao Carabao Mango Orchard',
    cropType: 'Carabao Mango',
    livestockType: undefined,
    description:
      'Premium Philippine carabao mango, best in the world. Export-certified orchard with contracts to Japan and South Korea buyers.',
    location: 'Davao del Norte',
    fundingGoal: 15000,
    currentFunding: 8200,
    expectedYield: '25 metric tons',
    expectedReturn: 42,
    riskLevel: 'HIGH',
    duration: 365,
    harvestSchedule: 'March 2026',
    status: 'ACTIVE',
    contractAddress: 'CCONTRACTEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE5',
    farmerWallet: 'GFARMER5EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE',
    cooperativeId: 'coop-2',
    cooperative: MOCK_COOPERATIVES[1],
    cooperativeEnabled: true,
    weatherRisk: 'HIGH',
    createdAt: '2025-01-15T00:00:00Z',
    updatedAt: '2025-05-15T00:00:00Z',
    _count: { investments: 17 },
  },
  {
    id: 'farm-6',
    name: 'Benguet Strawberry Valley',
    cropType: 'Strawberry',
    livestockType: undefined,
    description:
      'Mountain strawberry cultivation at 1500m elevation. Premium fresh strawberries supplied to Metro Manila supermarkets and restaurants.',
    location: 'La Trinidad, Benguet',
    fundingGoal: 4000,
    currentFunding: 1200,
    expectedYield: '2 metric tons fresh',
    expectedReturn: 25,
    riskLevel: 'MEDIUM',
    duration: 90,
    harvestSchedule: 'October 2025',
    status: 'PENDING',
    contractAddress: undefined,
    farmerWallet: 'GFARMER6FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
    cooperativeId: 'coop-1',
    cooperative: MOCK_COOPERATIVES[0],
    cooperativeEnabled: true,
    weatherRisk: 'MODERATE',
    createdAt: '2025-05-10T00:00:00Z',
    updatedAt: '2025-05-10T00:00:00Z',
    _count: { investments: 4 },
  },
]

export const MOCK_INVESTMENTS: Investment[] = [
  {
    id: 'inv-1',
    farmId: 'farm-1',
    farm: MOCK_FARMS[0],
    investorWallet: 'GINVESTORDEMO1AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    amount: 500,
    txHash: 'abc123def456abc123def456abc123def456abc123def456abc123def456abc1',
    status: 'ACTIVE',
    createdAt: '2025-03-10T00:00:00Z',
  },
  {
    id: 'inv-2',
    farmId: 'farm-2',
    farm: MOCK_FARMS[1],
    investorWallet: 'GINVESTORDEMO1AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    amount: 1000,
    txHash: 'def789ghi012def789ghi012def789ghi012def789ghi012def789ghi012def7',
    status: 'ACTIVE',
    createdAt: '2025-03-20T00:00:00Z',
  },
  {
    id: 'inv-3',
    farmId: 'farm-4',
    farm: MOCK_FARMS[3],
    investorWallet: 'GINVESTORDEMO1AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    amount: 750,
    txHash: 'ghi345jkl678ghi345jkl678ghi345jkl678ghi345jkl678ghi345jkl678ghi3',
    status: 'ACTIVE',
    returnAmount: 1012.5,
    createdAt: '2025-02-15T00:00:00Z',
  },
]

export const MOCK_TRANSACTIONS: Transaction[] = [
  {
    id: 'tx-1',
    txHash: 'abc123def456abc123def456abc123def456abc123def456abc123def456abc1',
    type: 'FUND',
    amount: 500,
    fromWallet: 'GINVESTORDEMO1AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    toWallet: 'CCONTRACTAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA1',
    farmId: 'farm-1',
    memo: 'Investment: Verde Rice Terraces',
    status: 'SUCCESS',
    createdAt: '2025-03-10T08:30:00Z',
  },
  {
    id: 'tx-2',
    txHash: 'def789ghi012def789ghi012def789ghi012def789ghi012def789ghi012def7',
    type: 'FUND',
    amount: 1000,
    fromWallet: 'GINVESTORDEMO1AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    toWallet: 'CCONTRACTBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB2',
    farmId: 'farm-2',
    memo: 'Investment: Bukidnon Corn Highlands',
    status: 'SUCCESS',
    createdAt: '2025-03-20T14:15:00Z',
  },
  {
    id: 'tx-3',
    txHash: 'ghi345jkl678ghi345jkl678ghi345jkl678ghi345jkl678ghi345jkl678ghi3',
    type: 'RETURN',
    amount: 1012.5,
    fromWallet: 'CCONTRACTDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD4',
    toWallet: 'GINVESTORDEMO1AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    farmId: 'farm-4',
    memo: 'Return: Ilocos Garlic & Onion Farm',
    status: 'SUCCESS',
    createdAt: '2025-05-01T10:00:00Z',
  },
]
